export const authActionType = {
    LOGIN: "LOGIN",
    FORGOT_PASSWORD: "FORGOT_PASSWORD",
    REMEMBER_ME: "REMEMBER_ME",
    SET_FORGOT_PASSWORD_DATA: "SET_FORGOT_PASSWORD_DATA",
    LOGOUT: "LOGOUT",
    CLEAR_ERROR_MESSAGE: "CLEAR_ERROR_MESSAGE",
    FIRST_TIME_RESET_PASSWORD: "FIRST_TIME_RESET_PASSWORD",
    SET_FIRST_TIME_RESET_PASSWORD_DATA: "SET_FIRST_TIME_RESET_PASSWORD_DATA",
    GET_BY_ID: "GET_BY_ID",
    GET_MY_ACCOUNT: "GET_MY_ACCOUNT",
    ERROR_MY_ACCOUNT: "ERROR_MY_ACCOUNT",
    SEND_EMAIL_FORGOT_PASSWORD: "SEND_EMAIL_FORGOT_PASSWORD",
    CHANGE_PASSWORD_FORGOT_PASSWORD: "CHANGE_PASSWORD_FORGOT_PASSWORD",
    UPDATE_MY_ACCOUNT: "UPDATE_MY_ACCOUNT",
    CHANGE_PASSWORD_MY_ACCOUNT: "CHANGE_PASSWORD_MY_ACCOUNT",
};

export const appActionType = {
    SET_LOADING: "SET_LOADING",
};

export const userActionType = {
    GET_LIST: "GET_LIST",
    GET_BY_ID: "GET_BY_ID",
    ADD_USER: "ADD_USER",
    ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
    ERROR_ADD_USER: "ERROR_ADD_USER",
};

export const sampleActionType = {
    GET_LIST: "GET_LIST",
    GET_LIST_NAME: "GET_LIST_NAME",
    GET_LIST_GENERATED: "GET_LIST_GENERATED",
    GET_BY_ID: "GET_BY_ID",
    GET_SAMPLE: "GET_SAMPLE",
    ADD_SAMPLE: "ADD_SAMPLE",
    SEARCH: "SEARCH",
    SEARCH_SAMPLES: "SEARCH_SAMPLES",
    EDIT_SAMPLE: "EDIT_SAMPLE",
    ASSIGN_TEST_TYPE: "ASSIGN_TEST_TYPE",
};

export const COCActionType = {
    GET_LIST: "GET_LIST",
    GET_BY_ID: "GET_BY_ID",
    GET_COC: "GET_COC",
    ADD_COC: "ADD_COC",
    ADD_COC_SUCCESS: "ADD_COC_SUCCESS",
    ERROR_ADD_COC: "ERROR_ADD_COC",
    EDIT_COC: "EDIT_COC",
    EDIT_COC_SUCCESS: "EDIT_COC_SUCCESS",
    ERROR: "ERROR",
    SEARCH: "SEARCH",
    UPLOAD_FILE: "UPLOAD_FILE",
    UPLOAD_FILE_S3: "UPLOAD_FILE_S3",
    REMOVE_FILE: "REMOVE_FILE",
    REMOVE_ALL_FILE: "REMOVE_ALL_FILE",
    GET_LIST_FILES: "GET_LIST_FILES",
    GET_FILE: "GET_FILE",
    GENERATE_REPORT: "GENERATE_REPORT",
    GET_LIST_SAMPLES_FILE: "GET_LIST_SAMPLES_FILE",
    GET_FILE_DETAIL: "GET_FILE_DETAIL",
    MAPPING_SAMPLE: "MAPPING_SAMPLE",
    ACCEPT_MAPPING: "ACCEPT_MAPPING",
    REJECT_MAPPING: "REJECT_MAPPING",
    GET_LIST_PHOTO: "GET_LIST_PHOTO",
    GET_REPORT_PARAMETER: "GET_REPORT_PARAMETER",
    GET_MAPPING_SAMPLE: "GET_MAPPING_SAMPLE",
};

export const TestTypeActionType = {
    GET_LIST: "GET_LIST",
};

export const CodeActionType = {
    GET_LIST: "GET_LIST",
    GET_LIST_ADDITIONAL: "GET_LIST_ADDITIONAL",
};

export const ParameterActionType = {
    GET_LIST: "GET_LIST",
    GET_LIST_OF_REGION: "GET_LIST_OF_REGION",
};

export const FileActionType = {
    GET_LIST: "GET_LIST",
    GET_FILE: "GET_FILE",
    GET_FILE_DETAIL: "GET_FILE_DETAIL",
    GET_FILE_SAMPLES: "GET_FILE_SAMPLES",
    UPLOAD_FILE: "UPLOAD_FILE",
    UPLOAD_FILE_S3: "UPLOAD_FILE_S3",
    REMOVE_FILE: "REMOVE_FILE",
    REMOVE_ALL_FILE: "REMOVE_ALL_FILE",
    GENERATE_REPORT: "GENERATE_REPORT",
    GET_REPORT_PARAMETER: "GET_REPORT_PARAMETER",
    GET_FORM_LAB_FILE: "GET_FORM_LAB_FILE",
    SAVE_FORM_LAB_FILE: "SAVE_FORM_LAB_FILE",
};

export const PhotoActionType = {
    GET_LIST: "GET_LIST",
    SEARCH_PHOTO: "SEARCH_PHOTO",
    GET_PHOTO_DETAIL: "GET_PHOTO_DETAIL",
    EXPORT_PHOTO: "EXPORT_PHOTO",
};

export const NotificationActionType = {
    GET_LIST: "GET_LIST",
    UPDATE_NOTIFICATION: "UPDATE_NOTIFICATION",
    MARK_NOTIFICATION: "MARK_NOTIFICATION",
};
